In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
data= pd.read_csv('Dataset.csv',on_bad_lines='skip')
data.head()

password  strength
0                zxe870819         1
1             xw46454nr23l         1
2                soporte13         1
3  accounts6000webhost.com         2
4                 c443balg         1

In [3]:
data['strength'].unique()

array([1, 2, 0], dtype=int64)

In [4]:
data['strength'].isna().sum()

0

In [5]:
data['password'].isna().sum()

0

In [68]:
#imbalaned dataset ; since majority of the password's strength are 1
data['strength'].value_counts()

strength
1    73883
0    13622
2    12495
Name: count, dtype: int64

In [7]:
#passing the entire dataset to the array named 'password_tupple'
password_tupple= np.array(data)
password_tupple

array([['zxe870819', 1],
       ['xw46454nr23l', 1],
       ['soporte13', 1],
       ...,
       ['czvrbun38', 1],
       ['mymyxe430', 1],
       ['glqjhkxb467', 1]], dtype=object)

In [8]:
#to make the model more ribust 
import random
random.shuffle(password_tupple)

In [9]:
#saperating independent (password) & dependent ( strength) features
x = [labels[0] for labels in password_tupple]
y = [labels[1] for labels in password_tupple]

In [10]:
x

['zxe870819',
 'xw46454nr23l',
 'zxe870819',
 'zxe870819',
 'zxe870819',
 '16623670p',
 'xw46454nr23l',
 'c443balg',
 'yj9q3f8p',
 'yin172015',
 '16623670p',
 'c443balg',
 'zxe870819',
 'c443balg',
 '16623670p',
 'bodrum1903',
 'c443balg',
 'muka2005',
 'konjina88',
 '35av2975z5',
 'muka2005',
 'oejcr710',
 '16623670p',
 'yj9q3f8p',
 '35av2975z5',
 'mihibo379',
 'jukutpaku321',
 'dpkashyap3',
 'djredd09',
 'c443balg',
 'oejcr710',
 'bedys583',
 'zxe870819',
 '4911501833ff',
 'soporte13',
 'Rtg9JEjY2MARgl1h',
 '4911501833ff',
 'soporte13',
 '3118163841n',
 'oraloral93',
 'djredd09',
 '180ZIRUVIcuFERy',
 'AVYziJyQevot714',
 'YzXtV6TUxMwoQKml',
 'killadude1',
 'qq1318242449',
 'muka2005',
 'heihei321',
 'heihei321',
 '9lvquzz55',
 'accounts6000webhost.com',
 'a226joyi',
 'Rtg9JEjY2MARgl1h',
 'Rtg9JEjY2MARgl1h',
 'yin172015',
 'YzXtV6TUxMwoQKml',
 'sapito22',
 'dtc5aoy',
 'taslim123',
 '0Y1QKoDUzOAb83Zs',
 'wvhwvo15',
 '9lvquzz55',
 'tripanosoma1',
 'oejcr710',
 'mihibo379',
 'jukutpaku321

In [11]:
y

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


**Applying TF-IDF on the data**

In [26]:
#before applying TF-IDF on the data , I need to make sure whether the data is string or not . Cause String type data is all we need 
def word_devide_char(inputs):
    character = []
    for i in inputs:
        character.append(i)
    return character

In [28]:
word_devide_char('yj9q3f8p')

['y', 'j', '9', 'q', '3', 'f', '8', 'p']

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
vectorized_data = TfidfVectorizer(tokenizer= word_devide_char)

In [35]:
X = vectorized_data.fit_transform(x)

In [37]:
X.shape

(100000, 81)

In [43]:
vectorized_data.get_feature_names_out()

array(['\x10', '\x11', ' ', '!', '#', '$', '%', '&', '(', ')', '*', '+',
       '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', 'a',
       'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{',
       '}', '~', '¡', '°', '±', '³', 'µ', 'ß', 'ä', 'æ', 'ç', 'õ', 'ö',
       'ú', 'ý', 'þ', '›'], dtype=object)

In [45]:
first_document_vector = X[0]
first_document_vector 

<1x81 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [47]:
#to get the data in vectorized form 
first_document_vector.T.todense()

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.27198716],
        [0.20936116],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.31450842],
        [0.6079751 ],
        [0.29109828],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.23404626],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [51]:
df= pd.DataFrame(data=first_document_vector.T.todense(),index=vectorized_data.get_feature_names_out(),columns=['TF-IDF'])
df.sort_values(by=['TF-IDF'],ascending=False)

TF-IDF
8   0.607975
x   0.380961
z   0.359158
7   0.314508
9   0.291098
..       ...
?   0.000000
>   0.000000
=   0.000000
<   0.000000
›   0.000000

[81 rows x 1 columns]

**Applying classification model on data**

In [70]:
#since the dataset is imbalanced ; we can't apply linear regression. 
#applying logistic regression on data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [72]:
X_train.shape

(80000, 81)

In [74]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0,multi_class='multinomial')

In [76]:
clf.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial', random_state=0)

In [84]:
#predict the model with the test data
y_pred = clf.predict(X_test)
y_pred

array([1, 1, 0, ..., 1, 1, 1])

In [80]:
#predict the model with random data
dt= np.array(['@ggerer#1314324'])
pred = vectorized_data.transform(dt)
clf.predict(pred)

array([1])

**Checking accuracy of model**

In [87]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm =  confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[  744  2034     2]
 [  474 13883   395]
 [    3   794  1671]]
0.8149


In [89]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.61      0.27      0.37      2780
           1       0.83      0.94      0.88     14752
           2       0.81      0.68      0.74      2468

    accuracy                           0.81     20000
   macro avg       0.75      0.63      0.66     20000
weighted avg       0.80      0.81      0.79     20000

